MyFarmer/Models/Farm.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace MyFarmer.Models
{
    public class Farm
    {
        public int Id { get; set; }
        [Required]
        public IdentityUser Farmer { get; set; }

        [Required, MinLength(1), MaxLength(255)]
        public string Name { get; set; }

        [Required, EmailAddress]
        public string Email { get; set; }

        [Required, Phone]
        public string Phone { get; set; }

        [Required, MinLength(1), MaxLength(500)]
        public string Address { get; set; }

        [MinLength(1), MaxLength(500)]
        public string Description { get; set; }
    }
}

MyFarmer/Models/Food.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyFarmer.Models
{
    public class Food
    {
        public int Id { get; set; }

        [Required, MinLength(1), MaxLength(255)]
        public string Description { get; set; }

    }
}

MyFarmer/Models/Service.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyFarmer.Models
{
    public class Service
    {
        public int Id { get; set; }

        [Required, MinLength(1), MaxLength(255)]
         public string Description { get; set; }

    }
}

MyFarmer/Pages/Account/DeleteUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Account
{
    [Authorize(Roles = "User, Farmer")]
    public class DeleteUserModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<DeleteUserModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteUserModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<DeleteUserModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public IdentityUser UserToDelete;

        public void OnGet()
        {
            UserToDelete = db.Users.FirstOrDefault(i => i.Id == Id);
        }

        public async Task<IActionResult> OnPostDeleteUser()
        {
            var userDelete = userManager.Users.FirstOrDefault(u => u.Id == Id);
            if (userDelete == null)
            {
                // Error Message
                TempData["message"] = $"User account was not found.";
                return RedirectToPage("/Account/UserProfile");
            }

            // delete role if user found
            var roleToDelete = userManager.GetRolesAsync(userDelete).Result.FirstOrDefault();
            await userManager.RemoveFromRoleAsync(userDelete, roleToDelete);
            var result = userManager.DeleteAsync(userDelete);
            // if delete success
            if (result.IsCompletedSuccessfully)
            {
                await signInManager.SignOutAsync();
                // Success message
                TempData["message"] = $"User {userDelete.Email} account is deleted.";
                return RedirectToPage("/Account/Login");
            }
            // Error message
            TempData["message"] = $"User {userDelete.Email} account was not deleted - error encountered.";
            return RedirectToPage("/Account/UserProfile");
        }
    }
}

MyFarmer/Pages/Admin/DeleteFarm.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteFarmModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteFarmModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public string Name { get; set; }

        public void OnPost()
        {
            var farm = db.Farms.FirstOrDefault(i => i.Id == Id);
            Name = farm.Name;
        }

        public IActionResult OnPostDeleteFarm()
        {
            var farmToDelete = db.Farms.FirstOrDefault(u => u.Id == Id);
            if (farmToDelete == null)
            {
                TempData["message"] = $"Farm account was not found.";
                return RedirectToPage("/Admin/Farms");
            }
            var ff = db.FarmsFoods.Where(f => f.Farm.Id == Id).ToList();
            if (ff != null)
            {
                db.FarmsFoods.RemoveRange(ff);
            }
            var fs = db.FarmsServices.Where(f => f.Farm.Id == Id).ToList();
            if (ff != null)
            {
                db.FarmsServices.RemoveRange(fs);
            }
            db.Farms.Remove(farmToDelete);
            db.SaveChanges();
            TempData["message"] = $"User {Name} account is deleted.";
            return RedirectToPage("/Admin/Farms");
        }
    }
}

MyFarmer/Pages/Admin/DeleteFarmFood.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteFarmFoodModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteFarmFoodModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Description { get; set; }
        public void OnPost()
        {
            var farmFood = db.FarmsFoods.FirstOrDefault(i => i.Id == Id);

        }

        public IActionResult OnPostDeleteFarmFood()
        {
            var fsToDelete = db.FarmsFoods.FirstOrDefault(u => u.Id == Id);
            if (fsToDelete == null)
            {
                TempData["message"] = $"Farm Food account was not found.";
                return RedirectToPage("/Admin/FarmFood");
            }
            db.FarmsFoods.Remove(fsToDelete);
            db.SaveChanges();
            TempData["message"] = $"Farm {Name} with Food {Description} was deleted";
            logger.LogInformation($"Farm {Name} with Food {Description} was deleted from database");
            return RedirectToPage("/Admin/FarmFood");
        }
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Admin/DeleteFarmService.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;


namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteFarmServiceModel : PageModel
    {

        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteFarmServiceModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Description { get; set; }
        public void OnPost()
        {
            var farmService = db.FarmsServices.FirstOrDefault(i => i.Id == Id);

        }

        public IActionResult OnPostDeleteFarmService()
        {
            var fsToDelete = db.FarmsServices.FirstOrDefault(u => u.Id == Id);
            if (fsToDelete == null)
            {
                TempData["message"] = $"Farm Service account was not found.";
                return RedirectToPage("/Admin/FarmService");
            }
            db.FarmsServices.Remove(fsToDelete);
            db.SaveChanges();
            TempData["message"] = $"Farm {Name} with Service {Description} was deleted";
            logger.LogInformation($"Farm {Name} with Service {Description} was deleted from database");
            return RedirectToPage("/Admin/FarmService");
        }
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Admin/DeleteFood.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteFoodModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteFoodModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public string Description { get; set; }

        public void OnPost()
        {
            var food = db.Foods.FirstOrDefault(i => i.Id == Id);
            Description = food.Description;
        }

        public IActionResult OnPostDeleteFood()
        {
            var foodToDelete = db.Foods.FirstOrDefault(u => u.Id == Id);
            if (foodToDelete == null)
            {
                TempData["message"] = $"Food account was not found.";
                return RedirectToPage("/Admin/Food");
            }
            db.Foods.Remove(foodToDelete);
            db.SaveChanges();
            TempData["message"] = $"Food {foodToDelete.Description} is deleted.";
            return RedirectToPage("/Admin/Food");
        }
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Admin/DeleteService.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteServiceModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteServiceModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public string Description { get; set; }

        public void OnPost()
        {
            var service = db.Servises.FirstOrDefault(i => i.Id == Id);
            Description = service.Description;
        }

        public IActionResult OnPostDeleteService()
        {
            var serviceToDelete = db.Servises.FirstOrDefault(u => u.Id == Id);
            if (serviceToDelete == null)
            {
                TempData["message"] = $"Service account was not found.";
                return RedirectToPage("/Admin/Service");
            }
            db.Servises.Remove(serviceToDelete);
            db.SaveChanges();
            TempData["message"] = $"Service {serviceToDelete.Description} is deleted.";
            return RedirectToPage("/Admin/Service");
        }
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Admin/Comments.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> userManager;
@model MyFarmer.Pages.Admin.CommentsModel
@{
    ViewData["Title"] = "AdminCommentsView";
}

<div class="container-fluid">
    <div class="row mb-5">

        <div class="col-12 text-center">
            <h1 class="mb-4">User Comments List</h1>
            <div>
                <input class="form-control mb-4" type="text" id="commentInput" onkeyup="commentFunction()"
                    placeholder="Search for User Email">
            </div>
            <div class="table-responsive table-striped">
                <table class="table" id="commentTable">
                    <thead class="bg-info text-white" style="position: sticky; top: 0; z-index: 10;">
                        <tr>
                            <th>Comment Id</th>
                            <th>User Email</th>
                            <th>Farm Name</th>
                            <th>Date</th>
                            <th>Message</th>
                            <th>Rating</th>
                             <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var c in Model.CommentList)
                        {
                            <tr>
                                <td>@c.Id</td>
                                <td>@c.Customer.Email</td>
                                <td>@c.Farm.Name</td>
                                <td>@c.Created.Date</td>
                                <td>@c.Message</td>
                                <td>@c.Rating</td>
                                <form action="" method="POST">
                                    <td><input type="submit" asp-route-id="@c.Id" value="View Detais"></td>
                                </form>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
             <a class="btn btn-info mt-4 btn-lg" asp-area="" asp-page="/Admin/Index">
            Back to Admin Interface</a>
        </div>

         <div class="col-12 my-5">
            @if (Model.Message != null)
            {
                <div class="alert alert-primary">
                    @Model.Message
                </div>
            }
            <div class="card mb-5">
                <div class="card-body mb-5">
                    <h4 class="text-center">User Comment Details</h4>
                    <form method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="Input.CommentId"></label>
                            <input asp-for="Input.CommentId" class="form-control" disabled />
                            <span asp-validation-for="Input.CommentId" class="text-danger"></span>
                        </div>

                         <div class="form-group">
                            <label asp-for="Input.UserEmail"></label>
                            <select asp-for="Input.UserEmail" class="form-control">
                                @foreach (var u in Model.UserList)
                                {
                                    <option>@u.Email</option>
                                }
                            </select>
                        </div>

                         <div class="form-group">
                            <label asp-for="Input.FarmName"></label>
                            <select asp-for="Input.FarmName" class="form-control">
                                @foreach (var f in Model.FarmList)
                                {
                                    <option>@f.Name</option>
                                }
                            </select>
                        </div>
                                           
                        <div class="form-group">
                            <label asp-for="Input.Date"></label>
                            <input asp-for="Input.Date" class="form-control"/>
                            <span asp-validation-for="Input.Date" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Input.Message"></label>
                            <input asp-for="Input.Message" class="form-control" />
                            <span asp-validation-for="Input.Message" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Input.Rating"></label>
                            <input asp-for="Input.Rating" class="form-control" />
                            <span asp-validation-for="Input.Rating" class="text-danger"></span>
                        </div> 

                          @if (Model.Input.CommentId < 1)
                        {
                            <button type="submit" class="btn btn-info btn-lg mr-4" asp-page-handler="AddComment">Add</button>
                        }
                        else
                        {
                            <div class="btn-group">
                                <button type="submit" class="btn btn-info btn-lg mr-4" asp-page-handler="UpdateComment"
                                asp-route-id="@Model.Input.CommentId">Update</button>
                                <button type="submit" class="btn btn-danger btn-lg" asp-page="/Admin/DeleteComment"
                                asp-route-id="@Model.Input.CommentId">Delete</button>
                            </div>

                        }
                    </form>
                    <form method="GET">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-info btn-lg mr-4" asp-page-handler="ClearForm">Clear
                                Form</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
       

    </div>
</div>


<script>
    function commentFunction() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("commentInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("commentTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>

MyFarmer/Pages/Admin/DeleteFarm.cshtml
@page "{id:min(1)}"
@model MyFarmer.Pages.Admin.DeleteFarmModel
@{
    ViewData["Title"] = "Delete Farm";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Farm Id: @Model.Id </p>
    <p>Farm Name: @Model.Name</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/Farms" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteFarm">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>

MyFarmer/Pages/Admin/DeleteFarmFood.cshtml
@page "{id:min(1)}/{name}/{description}"
@model MyFarmer.Pages.Admin.DeleteFarmFoodModel
@{
    ViewData["Title"] = "Delete Farm Food";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Farm Service Id: @Model.Id </p>
    <p>Farm Name: @Model.Name</p>
    <p>Service Name: @Model.Description</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/FarmFood" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteFarmFood">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>

MyFarmer/Pages/Admin/DeleteFarmService.cshtml
@page "{id:min(1)}/{name}/{description}"
@model MyFarmer.Pages.Admin.DeleteFarmServiceModel
@{
    ViewData["Title"] = "Delete Farm Service";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Farm Service Id: @Model.Id </p>
    <p>Farm Name: @Model.Name</p>
    <p>Service Name: @Model.Description</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/FarmService" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteFarmService">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>

MyFarmer/Pages/Admin/DeleteFood.cshtml
@page "{id:min(1)}"
@model MyFarmer.Pages.Admin.DeleteFoodModel
@{
    ViewData["Title"] = "Delete Food";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Food Id: @Model.Id </p>
    <p>Food Name: @Model.Description</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/Food" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteFood">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>

MyFarmer/Pages/Admin/DeleteService.cshtml
@page  "{id:min(1)}"
@model MyFarmer.Pages.Admin.DeleteServiceModel
@{
    ViewData["Title"] = "Delete Service";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Service Id: @Model.Id </p>
    <p>Service Name: @Model.Description</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/Service" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteService">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>

MyFarmer/Pages/Admin/DeleteUser.cshtml
@page "{id}"
@model MyFarmer.Pages.Admin.DeleteUserModel
@{
    ViewData["Title"] = "Delete User";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Id: @Model.Id</p>
    <p>Name: @Model.Email</p>
    <p>Email: @Model.Email</p>
    <br>
    <h5>Are you sure you want to delete this record?</h5>
    <br>
    <a asp-page="/Admin/Users" class="btn btn-info btn-lg mr-4">Cancel</a>
    <br><br>
    <form  asp-page-handler="DeleteUser">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Yes, Delete" class="btn btn-danger btn-lg" />
    </form>

</div>