MyFarmer/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFarmer.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Admin/DeleteFarm.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteFarmModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<UsersModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteFarmModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<UsersModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public string Name { get; set; }

        public void OnPost()
        {
            var farm = db.Farms.FirstOrDefault(i => i.Id == Id);
            Name = farm.Name;
        }

        public IActionResult OnPostDeleteFarm()
        {
            var farmToDelete = db.Farms.FirstOrDefault(u => u.Id == Id);
            if (farmToDelete == null)
            {
                TempData["message"] = $"Farm account was not found.";
                return RedirectToPage("/Admin/Farms");
            }
            var ff = db.FarmsFoods.Where(f => f.Farm.Id == Id).ToList();
            if (ff != null)
            {
                db.FarmsFoods.RemoveRange(ff);
            }
            var fs = db.FarmsServices.Where(f => f.Farm.Id == Id).ToList();
            if (ff != null)
            {
                db.FarmsServices.RemoveRange(fs);
            }
            db.Farms.Remove(farmToDelete);
            db.SaveChanges();
            TempData["message"] = $"User {Name} account is deleted.";
            return RedirectToPage("/Admin/Farms");
        }
    }
}

MyFarmer/Pages/DeleteFarm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;

namespace MyFarmer.Pages
{
    [Authorize(Roles = "Farmer")]
    public class DeleteFarmModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<DeleteFarmModel> logger;
        public DeleteFarmModel(MyFarmerDbContext db, ILogger<DeleteFarmModel> logger)
        {
            this.db = db;
            this.logger = logger;
        }
        [BindProperty]
        public Farm MyFarm {get;set;}
        [TempData]
        public string Message { get; set; }
        [BindProperty(SupportsGet =true)]
        public int Id { get; set; }
        public IActionResult OnGet()
        {
            //Get the Farm by Id
            MyFarm = db.Farms.FirstOrDefault(Farm=>Farm.Id==Id);
            if(MyFarm == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            Farm farmToDelete = db.Farms.FirstOrDefault(Farm=>Farm.Id==Id);
            if (farmToDelete == null)
            {
                logger.LogInformation($"Farm with is {Id} was not found.");
                return RedirectToPage("/NotFound");
            }
            //TODO: Step back if one of transactions failed 
            // Get all records from FarmsFood and delete them
            IList<FarmsFood> farmsFoodToDelete = db.FarmsFoods.Where(item => item.Farm == farmToDelete).ToList();
            db.FarmsFoods.RemoveRange(farmsFoodToDelete);
            // Get all records from FarmsService and delete them
            IList<FarmsService> farmsServicesToDelete = db.FarmsServices.Where(item => item.Farm == farmToDelete).ToList();
            db.FarmsServices.RemoveRange(farmsServicesToDelete);
            // Get all records from FarmImage and delete them
            IList<FarmImage> farmsImagesToDelete = db.FarmImages.Where(item => item.Farm == farmToDelete).ToList();
            db.FarmImages.RemoveRange(farmsImagesToDelete);
            // Remove the farm
            db.Farms.Remove(farmToDelete);
            db.SaveChanges();
            TempData["message"] = $"The farm {farmToDelete.Name} was deleted";
            return RedirectToPage("/FarmsList");
        }
    }
}

MyFarmer/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyFarmer.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyFarmer/Pages/FarmDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;

namespace MyFarmer.Pages
{
    [Authorize]
    public class FarmDetailsModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<FarmDetailsModel> logger;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;

        public FarmDetailsModel(MyFarmerDbContext db, ILogger<FarmDetailsModel> logger, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            this.db = db;
            this.logger = logger;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }
        // Farm Id
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        [TempData]
        public string Message { get; set; }

        public InputModelFarm InputFarm { get; set; }

        public class InputModelFarm
        {
            public int FarmId { get; set; }


            [Display(Name = "Farmer Name")]
            public IdentityUser Farmer { get; set; }


            [Display(Name = "Farm Name")]
            public string Name { get; set; }


            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }


            [DataType(DataType.PhoneNumber)]
            [Display(Name = "Phone")]
            public string Phone { get; set; }

            [Required]
            [Display(Name = "Farm Address")]
            public string Address { get; set; }


            [Display(Name = "Farm Description")]
            public string Description { get; set; }
        }

        [BindProperty]
        public InputModelAddReview InputReview { get; set; }

        public class InputModelAddReview
        {
            public IdentityUser Customer { get; set; }

            public string FarmName { get; set; }

            [DataType(DataType.DateTime)]
            public DateTime Created { get; set; }

            [Required, MinLength(1), MaxLength(2000)]
            [Display(Name = "Post Content:")]
            public string Message { get; set; }

            [Range(0, 5, ErrorMessage = "Rating must be between 0-5")]
            [Display(Name = "Rating / 5:")]
            public int Rating { get; set; }

        }
        public List<FarmsFood> FarmsFoods = new List<FarmsFood>();
        public List<FarmsService> FarmsServices = new List<FarmsService>();
        public List<FarmImage> FarmsImages = new List<FarmImage>();

        public List<CustomerComment> custCommentsList { get; set; } = new List<CustomerComment>();

        public IdentityUser CurrentUser;
        public IActionResult OnGet()
        {
            custCommentsList = db.CustomerComments.Include(f => f.Farm).Include(c => c.Customer).OrderByDescending(c => c.Created).ToList();
            InputReview = new InputModelAddReview();
            CurrentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
            InputReview.Customer = CurrentUser;
            // Try to get Farm By Id
            var farm = db.Farms.Include(farm => farm.Farmer).FirstOrDefault(farm => farm.Id == Id);
            if (farm == null)
            {
                logger.LogError($"Can't find farm with Id:{Id}");
                return RedirectToPage("/NotFound");
            }
            InputReview.FarmName = farm.Name;
            // If farm exist than get data
            InputFarm = new InputModelFarm();
            InputFarm.FarmId = farm.Id;
            InputFarm.Farmer = farm.Farmer;
            InputFarm.Name = farm.Name;
            InputFarm.Email = farm.Email;
            InputFarm.Phone = farm.Phone;
            InputFarm.Address = farm.Address;
            InputFarm.Description = farm.Description;
            // Get Food list based on Farm Id
            FarmsFoods = db.FarmsFoods.Include(farm => farm.Farm).Include(farm => farm.FarmFood).Where(farm => farm.Farm.Id == Id).ToList();
            // Get Services list based on Farm Id
            FarmsServices = db.FarmsServices.Include(farm => farm.Farm).Include(farm => farm.FarmService).Where(farm => farm.Farm.Id == Id).ToList();
            // Get Services list based on Farm Id
            FarmsImages = db.FarmImages.Include(farm => farm.Farm).Where(farm => farm.Farm.Id == Id).ToList();
            return Page();
        }
        public async Task<IActionResult> OnPostReview()
        {
            if (ModelState.IsValid)
            {
                CustomerComment newPost = new CustomerComment();
                newPost.Customer = userManager.FindByNameAsync(User.Identity.Name).Result;
                // Try to get Farm By Id
                var farm = db.Farms.Include(farm => farm.Farmer).FirstOrDefault(farm => farm.Id == Id);
                newPost.Farm = farm;
                InputReview.Created = DateTime.Now;
                newPost.Created = InputReview.Created;
                newPost.Message = InputReview.Message;
                newPost.Rating = InputReview.Rating;
                db.CustomerComments.Add(newPost);
                db.SaveChanges();
                logger.LogInformation($"Post was successfully added to the database");
                Message = $"Review was successfully added.";
                return RedirectToPage("/FarmDetails");

            }
            else
            {
                InputReview = new InputModelAddReview();
                CurrentUser = userManager.Users.FirstOrDefault(i => i.UserName == @User.Identity.Name);
                InputReview.Customer = CurrentUser;
                custCommentsList = db.CustomerComments.Include(f => f.Farm).Include(c => c.Customer).OrderByDescending(c => c.Created).ToList();

                // Try to get Farm By Id
                var farm = db.Farms.Include(farm => farm.Farmer).FirstOrDefault(farm => farm.Id == Id);
                if (farm == null)
                {
                    logger.LogError($"Can't find farm with Id:{Id}");
                    return RedirectToPage("/NotFound");
                }
                InputReview.FarmName = farm.Name;
                // If farm exist than get data
                InputFarm = new InputModelFarm();
                InputFarm.FarmId = farm.Id;
                InputFarm.Farmer = farm.Farmer;
                InputFarm.Name = farm.Name;
                InputFarm.Email = farm.Email;
                InputFarm.Phone = farm.Phone;
                InputFarm.Address = farm.Address;
                InputFarm.Description = farm.Description;

                // Get Food list based on Farm Id
                FarmsFoods = db.FarmsFoods.Include(farm => farm.Farm).Include(farm => farm.FarmFood).Where(farm => farm.Farm.Id == Id).ToList();
                // Get Services list based on Farm Id
                FarmsServices = db.FarmsServices.Include(farm => farm.Farm).Include(farm => farm.FarmService).Where(farm => farm.Farm.Id == Id).ToList();
                // Get Services list based on Farm Id
                FarmsImages = db.FarmImages.Include(farm => farm.Farm).Where(farm => farm.Farm.Id == Id).ToList();

                logger.LogInformation($"Error adding post to database");
                Message = $"An error occured while adding your post.";
                return Page();
            }
        }
    }

}

MyFarmer/Pages/FarmsList.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;

namespace MyFriends2.Pages
{
    [Authorize(Roles = "Farmer")]
    public class FarmsListModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<AddFarmModel> logger;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;

        public FarmsListModel(MyFarmerDbContext db, ILogger<AddFarmModel> logger,SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            this.db = db;
            this.logger = logger;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }
        [BindProperty]
        public List<Farm> FarmList {get;set;}
        [BindProperty]
        public IdentityUser Farmer { get; set; }
        [TempData]
        public string Message { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            // Get the user
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            Farmer = user;
            //get the list of the farm for defined user
            FarmList = db.Farms.Include(farm => farm.Farmer).Where(farm => farm.Farmer.Id == user.Id).ToList();

            return Page();
        }
    }
}

MyFarmer/Pages/InternalError.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFriends2.Pages
{
    public class InternalErrorModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFriends2.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyFarmer.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/AccessDenied.cshtml
@page
@model MyFarmer.Pages.AccessDeniedModel
@{
    ViewData["Title"] = "Access Denied";
}
<h4>Access Denied</h4>
<a class="nav-link" asp-area="" asp-page="/Index">Click here to continue.</a>

MyFarmer/Pages/DeleteFarm.cshtml
@page "{id:int}"
@model MyFarmer.Pages.DeleteFarmModel
@{
    ViewData["Title"] = "Delete Farm";
}
<div class="container">
    <div class="row">  
        <div class="col-md-6 offset-3">
            <h4>Confirmation to delete the farm</h4>
            <div class="card">
                <div class="card-header">
                    <span class="font-weight-bold">Farm name: </span>@Model.MyFarm.Name
                </div>
                <div class="card-body">
                    <p><span class="font-weight-bold">Email: </span>@Model.MyFarm.Email</p>
                    <p><span class="font-weight-bold">Phone: </span>@Model.MyFarm.Phone</p>
                    <p><span class="font-weight-bold">Address: </span>@Model.MyFarm.Address</p>
                </div>
                <div class="card-footer">
                    <form method="post">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a asp-page="/FarmDetails" asp-route-id="@Model.MyFarm.Id" class="btn btn-primary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>  
    </div>
</div>

MyFarmer/Pages/FarmDetails.cshtml
@page "{id:int}"
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> userManager;
@model MyFarmer.Pages.FarmDetailsModel
@{
    ViewData["Title"] = "Farm Details";
    string Role = "";
    if (signInManager.IsSignedIn(User))
    {
        var userName = User.Identity.Name;
        var user = await userManager.FindByNameAsync(userName);
        var roles = await userManager.GetRolesAsync(user);
        //NOTIFICATION: Multiple roles are not supported.
        foreach (var role in roles)
        {
            Role = role;
        }
    }
}
<div class="Container">
    @if (Model.Message != null)
    {
        @if (Model.Message.Contains("error"))
        {
            <div>
                <div class="alert alert-danger">
                    @Model.Message
                </div>
            </div>
        }
        else
        {
            <div>
                <div class="alert alert-success">
                    @Model.Message
                </div>
            </div>
        }
    }
    <div id="indexCarousel" class="carousel slide" data-ride="carousel">

        <div class="carousel-inner">
            @foreach (var item in @Model.FarmsImages)
            {
                var photoPath = "/Uploads/" + @item.ImageName;
                <div class="carousel-item active">
                    <img class="d-block w-100 img-fluid" src="@photoPath" alt="First slide">
                </div>
            }
        </div>
        <a class="carousel-control-prev display-4" href="#indexCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#indexCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row mt-4">
        <div class="col-md-9 mb-4">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <h4 class="card-title">@Model.InputFarm.Name</h4>
                    <p class="h4">Rating: 4</p>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><span class="font-weight-bold">Email: </span>@Model.InputFarm.Email
                        </li>
                        <li class="list-group-item"><span class="font-weight-bold">Phone: </span>@Model.InputFarm.Phone
                        </li>
                        <li class="list-group-item"><span class="font-weight-bold">Address:
                            </span>@Model.InputFarm.Address</li>
                        <li class="list-group-item"><span class="font-weight-bold">Description:
                            </span>@Model.InputFarm.Description</li>
                    </ul>
                </div>
                @if (Role == "Farmer")
                {
                    <div class="card-footer">
                        <a asp-page="/AddFarm" asp-route-id="@Model.InputFarm.FarmId" class="btn btn-primary">Edit</a>
                        <a asp-page="/DeleteFarm" asp-route-id="@Model.InputFarm.FarmId" class="btn btn-danger">Delete</a>
                    </div>
                }
            </div>
            @if (Role == "User")
            {
                <form method="POST">
                    <div class="card">
                        <div class="card-header">
                            <h4>Post a Review for @Model.InputFarm.Name</h4>
                        </div>
                        <div class="card-body">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="InputReview.Message"></label>
                                <textarea asp-for="InputReview.Message" class="form-control" cols="30" rows="5"></textarea>
                                <span asp-validation-for="InputReview.Message" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="InputReview.Rating"></label>
                                <input asp-for="InputReview.Rating" class="form-control" type="number" />
                                <span asp-validation-for="InputReview.Rating" class="text-danger"></span>
                            </div>
                            <div class="btn-group">
                                <button asp-page-handler="Review" type="submit" class="btn btn-primary btn-md mr-4">Post
                                    Review</button>
                            </div>
                        </div>
                    </div>
                </form>
            }
            <div class="card h-25 mt-4">
                <div class="card-header">
                    <h3 class="mt-2">Reviews</h3>
                </div>

                <div class="card-body overflow-auto">
                    @if (@Model.custCommentsList.Any())
                    {
                        <div class="list-group">
                            <div class="list-group-item list-group-item-action flex-column align-items-start p-0 border-0">

                                @foreach (var c in @Model.custCommentsList)
                                {

                                    @if (c.Farm.Id == @Model.InputFarm.FarmId)
                                    {
                                        <div class="border mb-1 p-2">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">@c.Customer.UserName</h5>
                                                <small>Post Created On: @c.Created</small>
                                            </div>
                                            <p class="mt-2 mb-1">@c.Message</p>
                                            <div class="d-flex w-100 justify-content-between mt-3">
                                                <small>Rating: @c.Rating/5</small>
                                                <small>Farm: @c.Farm.Name</small>
                                            </div>
                                            @if (Role == "User")
                                            {
                                                @if (c.Customer.UserName == User.Identity.Name)
                                                {

                                                    <div class="d-inline d-flex justify-content-between mt-3">
                                                        <a asp-page="/Account/EditPost" asp-route-id="@c.Id" class="btn btn-sm btn-primary"
                                        role="button">Edit</a>
                                                        <a asp-page="/Account/DeletePost" asp-route-id="@c.Id" class="btn btn-sm btn-danger"
                                        role="button">Delete Post</a>
                                                    </div>
                                                }


                                            }
                                        </div>
                                    }

                                }
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="text-center mt-5">
                            <h4 class="text-warning">This farm does not have any post yet. Be the first to leave a review!
                            </h4>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card mb-4">
                <div class="card-header">
                    <p class="h4">Farms food</p>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        @foreach (var item in @Model.FarmsFoods)
                        {
                            if (item.IsChecked == true)
                            {
                                <li class="list-group-item">@item.FarmFood.Description</li>
                            }
                        }
                    </ul>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-header">
                    <p class="h4">Farms services</p>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        @foreach (var item in @Model.FarmsServices)
                        {
                            if (item.IsChecked == true)
                            {
                                <li class="list-group-item">@item.FarmService.Description</li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

MyFarmer/Pages/FarmsList.cshtml
@page
@model MyFriends2.Pages.FarmsListModel
@{
    ViewData["Title"] = "Farms List";
}
<div class="container">
    <h4 class="my-4">Farms list for Farmer @Model.Farmer.UserName</h4>
    @if (Model.Message != null)
    {
        <div>
            <div class="alert alert-success">
                @Model.Message
            </div>
        </div>
    }
    <div class="row">
        @foreach (var farm in @Model.FarmList)
        {
            <div class="col-md-4">
                <div class="card my-4">
                    <div class="card-header">
                        <span class="font-weight-bold">Farm name: </span>@farm.Name
                    </div>
                    <div class="card-body">
                        <p><span class="font-weight-bold">Email: </span>@farm.Email</p>
                        <p><span class="font-weight-bold">Phone: </span>@farm.Phone</p>
                        <p><span class="font-weight-bold">Address: </span>@farm.Address</p>
                    </div>
                    <div class="card-footer">
                        <a asp-page="/FarmDetails" asp-route-id="@farm.Id" class="btn btn-primary">details → </a>
                    </div>
                </div>
            </div>
        }    
    </div>
</div>

MyFarmer/Pages/InternalError.cshtml
@page
@model MyFriends2.Pages.InternalErrorModel
@{
    ViewData["Title"] = "Internal error";
}
<div class="container">
    @if (Model.Message != null)
    {
        <div>
            <div class="alert alert-success">
                @Model.Message
            </div>
        </div>
    }
    <p>Internal Error. Please contact with administrator
        <a class="nav-link" asp-area="" asp-page="/Index">Click to continue.</a>
    </p>
</div>

MyFarmer/Pages/NotFound.cshtml
@page
@model MyFriends2.Pages.NotFoundModel
@{
    ViewData["Title"] = "Page not found";
}
<div class="text-center">
    <h4>Page not found</h4>
    <img src="/Images/construction.png" alt="Construction Workers">
    <p>It seems like you've landed on a page that our awesome dedicated programmers are currently building. Please come
        back
        later!<a class="nav-link" asp-area="" asp-page="/Index">Click here to continue.</a></p>
</div>

MyFarmer/Pages/SearchResult.cshtml
@page
@model MyFarmer.Pages.SearchResultModel
@{
    ViewData["Title"] = "Search Result";
}

<div class="container">
    <h2 class="search-header">Results for: <span class="h3"><mark>@Model.keywords</mark></span></h2>
    <hr>

    @* @Html.ValidationSummary(false, "", new { @class = "text-danger" }) *@

    <div class="list-group">

        @foreach (var farm in Model.FarmsList)
        {
            <a asp-page="/FarmDetails" asp-route-id="@farm.Id" class="list-group-item list-group-item-action">@farm.Address,
                @farm.Name</a>
        }
    </div>

</div>