MyFarmer/Pages/Account/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;

namespace MyFarmer.Pages.Account
{
    [Authorize(Roles = "User, Farmer")]
    public class ChangePasswordModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<ChangePasswordModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;

        [TempData]
        public string Message { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public ChangePasswordModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<ChangePasswordModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }
        public IdentityUser currUser;

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            // public string UserId { get; set; }

            [Required]
            [DataType(DataType.Password, ErrorMessage = "Current password required")]
            [Display(Name = "Current Password:")]
            public string CurrentPassword { get; set; }

            [Required]
            [Display(Name = "New Password:")]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            public string NewPassword { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password:")]
            [Compare("NewPassword", ErrorMessage = "New password and confirmation password do not match.")]
            public string NewPasswordConfirm { get; set; }

        }
        public void OnGet()
        {
            currUser = userManager.Users.FirstOrDefault(i => i.UserName == @User.Identity.Name);
            if (currUser == null)
            {
                RedirectToPage("/Account/Login");
            }
        }
        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                // get user
                var user = userManager.Users.FirstOrDefault(i => i.Id == Id);

                // if null, redirect
                if (user == null)
                {
                    return RedirectToPage("/Account/UserProfile");
                }

                // update password
                var result = await userManager.ChangePasswordAsync(user, Input.CurrentPassword, Input.NewPassword);

                // if result does not succeed, add errors to the model state and re-render the ChangePassword view
                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    currUser = userManager.Users.FirstOrDefault(i => i.Id == Id);

                    return Page();
                }

                //  refresh sign in cookie and re-direct user to UserProfile page
                await signInManager.RefreshSignInAsync(user);
                Message = $"Password updated successfully.";
                return RedirectToPage("/Account/UserProfile");
            }

            // if modelState is not valid, re-render page
            currUser = userManager.Users.FirstOrDefault(i => i.Id == Id);
            return Page();
        }


    }
}

MyFarmer/Pages/Account/DeletePost.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Account
{
    [Authorize(Roles = "User")]
    public class DeletePostModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<DeleteUserModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeletePostModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<DeleteUserModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public CustomerComment PostToDelete;

        public void OnGet()
        {
            PostToDelete = db.CustomerComments.FirstOrDefault(c => c.Id == Id);
        }

        public async Task<IActionResult> OnPostDeletePost()
        {
            var postDelete = db.CustomerComments.FirstOrDefault(p => p.Id == Id);
            if (postDelete == null)
            {
                // Error Message
                TempData["message"] = $"Post was not found.";
                return RedirectToPage("/Account/UserProfile");
            }

            // delete post if post found
            db.CustomerComments.Remove(postDelete);
            db.SaveChanges();
            TempData["message"] = $"Post deleted successfully.";
            return RedirectToPage("/Account/UserProfile");
        }
    }
}

MyFarmer/Pages/Account/DeleteUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Globalization;

namespace MyFarmer.Pages.Account
{
    [Authorize(Roles = "User, Farmer")]
    public class DeleteUserModel : PageModel
    {
        private readonly MyFarmerDbContext db;
        private readonly ILogger<DeleteUserModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;
        public DeleteUserModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<DeleteUserModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public IdentityUser UserToDelete;

        public void OnGet()
        {
            UserToDelete = db.Users.FirstOrDefault(i => i.Id == Id);
        }

        public async Task<IActionResult> OnPostDeleteUser()
        {
            var userDelete = userManager.Users.FirstOrDefault(u => u.Id == Id);
            if (userDelete == null)
            {
                // Error Message
                TempData["message"] = $"User account was not found.";
                return RedirectToPage("/Account/UserProfile");
            }

            // delete role if user found
            var roleToDelete = userManager.GetRolesAsync(userDelete).Result.FirstOrDefault();
            await userManager.RemoveFromRoleAsync(userDelete, roleToDelete);
            var result = userManager.DeleteAsync(userDelete);
            // if delete success
            if (result.IsCompletedSuccessfully)
            {
                await signInManager.SignOutAsync();
                // Success message
                TempData["message"] = $"User {userDelete.Email} account is deleted.";
                return RedirectToPage("/Account/Login");
            }
            // Error message
            TempData["message"] = $"User {userDelete.Email} account was not deleted - error encountered.";
            return RedirectToPage("/Account/UserProfile");
        }
    }
}

MyFarmer/Pages/Account/EditPost.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyFarmer.Data;
using MyFarmer.Models;
using Microsoft.AspNetCore.Authorization;

namespace MyFarmer.Pages.Account
{
    [Authorize(Roles = "User")]
    public class EditPostModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        [TempData]
        [BindProperty]
        public string Message { get; set; }
        private readonly MyFarmerDbContext db;
        private readonly ILogger<EditUserModel> logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        private readonly RoleManager<IdentityRole> roleManager;

        public class InputModel
        {
            public int postId { get; set; }

            // [Required]
            // [Display(Name = "Username:")]
            // public IdentityUser Customer { get; set; }

            [Display(Name = "Posted By::")]
            public string Username;

            // [Required]
            // [Display(Name = "Farm Name: ")]
            // public Farm Farm { get; set; }

            [Display(Name = "Farm Name:")]
            public string FarmName;

            // [Required]
            [Display(Name = "Date Posted:")]
            [DataType(DataType.DateTime)]
            public DateTime Created { get; set; }

            [Required, MinLength(1), MaxLength(2000)]
            [Display(Name = "Post Content:")]
            public string Message { get; set; }

            [Range(0, 5, ErrorMessage = "Rating must be between 0-5")]
            [Display(Name = "Rating:")]
            public int Rating { get; set; }

        }

        public EditPostModel(MyFarmerDbContext db, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<EditUserModel> logger, RoleManager<IdentityRole> roleManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
            this.roleManager = roleManager;
        }

        public CustomerComment post;
        public Farm farm;

        public void OnGet()
        {
            Input = new InputModel();
            post = db.CustomerComments.Include(f => f.Farm).FirstOrDefault(p => p.Id == Id);
            farm = post.Farm;
            // FIXME: linq query failed
            // farm = db.CustomerComments.Include(f => f.Farm.Id == )
            // FarmList = db.Farms.Include(farm => farm.Farmer).Where(farm => farm.Farmer.Id == user.Id).ToList();

            Input.postId = post.Id;
            Input.Username = @User.Identity.Name;
            Input.FarmName = farm.Name;
            Input.Created = post.Created;
            Input.Message = post.Message;
            Input.Rating = post.Rating;
            // db.Frams.FromSQLRAw
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                // retrieve post to update
                var postUpdate = db.CustomerComments.Include(f => f.Farm).Include(u => u.Customer).FirstOrDefault(p => p.Id == Id);
                if (postUpdate != null)
                {
                    postUpdate.Created = DateTime.Now;
                    postUpdate.Message = Input.Message;
                    postUpdate.Rating = Input.Rating;
                    db.CustomerComments.Update(postUpdate);
                    db.SaveChanges();
                    logger.LogInformation($"Post {Id} succesfully updated.");
                    Message = $"Post succesfully updated.";
                }
                return RedirectToPage("/Account/UserProfile");

            }
            else
            {

                post = db.CustomerComments.Include(f => f.Farm).FirstOrDefault(p => p.Id == Id);
                farm = post.Farm;


                Input.postId = post.Id;
                Input.Username = @User.Identity.Name;
                Input.FarmName = farm.Name;
                Input.Created = post.Created;
                Input.Message = post.Message;
                Input.Rating = post.Rating;
                return Page();
            }

        }


    }
}

MyFarmer/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using MyFarmer.Models;

namespace MyFarmer.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly ILogger<LoginModel> logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            this.signInManager = signInManager;
            this.logger = logger;
        }
        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }
        }
        [TempData]
        public string Message { get; set; }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(Input.Email, Input.Password, false, true);
                if (result.Succeeded)
                {
                    logger.LogInformation($"User {Input.Email} logged in");
                    TempData["message"] = $"User {Input.Email} logged in";
                    return RedirectToPage("/Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Login failed");
                }
            }
            return Page();
        }
    }
}

MyFarmer/Pages/Account/RegisterSuccess.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFarmer.Pages.Account
{
    public class RegisterSuccessModel : PageModel
    {
       [BindProperty(SupportsGet = true)]
        public string Email { get; set;}
        public void OnGet()
        {
        }
    }
}

MyFarmer/Pages/Account/ChangePassword.cshtml
@page "{id}"
@model MyFarmer.Pages.Account.ChangePasswordModel
@{
    ViewData["Title"] = "Change Password";
}

<div class="container">
    <div class="text-center">
        <h1 class="text-warning profile-header">Change My Password</h1>
    </div>

    <div class="container d-flex justify-content-center mt-5" style="margin-bottom: 10rem !important;">
        <div class="card w-75">
            <div class="card-body">

                <form method="POST">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    @* <input type="hidden" asp-for="Input.postId" readonly> *@

                    <div class="form-group">
                        <label asp-for="Input.CurrentPassword"></label>
                        <input type="password" asp-for="Input.CurrentPassword" class="form-control" />
                        <span asp-validation-for="Input.CurrentPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.NewPassword"></label>
                        <input type="password" asp-for="Input.NewPassword" class="form-control" />
                        <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.NewPasswordConfirm"></label>
                        <input type="password" asp-for="Input.NewPasswordConfirm" class="form-control" />
                        <span asp-validation-for="Input.NewPasswordConfirm" class="text-danger"></span>
                    </div>

                    <div class="btn-group">
                        <a asp-page="/Account/UserProfile" class="btn btn-md btn-primary mr-4" role="button">Cancel</a>
                        <button type="submit" class="btn btn-primary btn-md mr-4">Update Password</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>


@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/DeletePost.cshtml
@page "{id}"
@model MyFarmer.Pages.Account.DeletePostModel
@{
    ViewData["Title"] = "Delete User";
}

<div class="container text-center">
    <h1 class="text-danger profile-header">Delete My Post</h1>
    <p class="note note-danger mt-2">
        <strong>Note:</strong> This action is <u>irreversible</u>!
    </p>

    <div class="container d-flex justify-content-center mt-5">
        <div class="card w-50">
            <div class="card-body">
                <h5 class="card-title">Post Info:</h5>
                <p><span class="large mark">Written by:</span> @User.Identity.Name</p>
                <p><span class="large mark">Comment:</span> @Model.PostToDelete.Message</p>
                <p><span class="large mark">Comment:@Model.PostToDelete.Created</span></p>


                <form asp-page-handler="DeletePost">
                    <input type="hidden" asp-for="@Model.Id" />
                    <a asp-page="/Account/UserProfile" class="btn btn-md btn-primary mr-4" role="button">Cancel</a>
                    <button type="submit" class="btn btn-danger btn-md">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/DeleteUser.cshtml
@page "{id}"
@model MyFarmer.Pages.Account.DeleteUserModel
@{
    ViewData["Title"] = "Delete Account";
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> userManager;
@{
    string Role = "";
    if (signInManager.IsSignedIn(User))
    {
        var userName = User.Identity.Name;
        var user = await userManager.FindByNameAsync(userName);
        var roles = await userManager.GetRolesAsync(user);
        //NOTIFICATION: Multiple roles are not supported.
        foreach (var role in roles)
        {
            Role = role;
        }
    }

}

@if (Role == "User")
{
    <div class="container text-center">
    <h1 class="text-danger profile-header">Delete My Account</h1>
    <p class="note note-danger mt-2">
        <strong>Note:</strong> This action will delete everything related to your account, including your reviews, and
        it is <u>irreversible</u>!
    </p>

    <div class="container d-flex justify-content-center mt-5">
        <div class="card w-50">
            <div class="card-body">
                <h5 class="card-title">Info:</h5>
                <p><span class="large mark">Username:</span> @User.Identity.Name</p>
                <p><span class="large mark">Email:</span> @Model.UserToDelete.Email</p>


                <form asp-page-handler="DeleteUser">
                    <input type="hidden" asp-for="@Model.Id" />
                    <a asp-page="/Account/UserProfile" class="btn btn-md btn-primary mr-4" role="button">Cancel</a>
                    <button type="submit" class="btn btn-danger btn-md">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
}
else if (Role == "Farmer")
{
    <div class="container text-center">
    <h1 class="text-danger profile-header">Delete My Account</h1>
    <p class="note note-danger mt-2">
        <strong>Note:</strong>For <u>security reasons</u>, farmers are not allowed to delete their account manually for
        now.
        This functionnality is coming soon!
    </p>

    <a asp-page="/Account/UserProfile" class="btn btn-md btn-primary mr-4" role="button">Back to Profile</a>
</div>
}



@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/EditPost.cshtml
@page "{id}"
@model MyFarmer.Pages.Account.EditPostModel
@{
    ViewData["Title"] = "Edit Post";
}

<div class="container">
    <div class="text-center">
        <h1 class="text-warning profile-header">Edit My Post:</h1>
    </div>

    <div class="container d-flex justify-content-center mt-5" style="margin-bottom: 10rem !important;">
        <div class="card w-75">
            <div class="card-body">

                <form method="POST">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="Input.postId" readonly>
                    <p class="d-inline"><span class="mark">Posted By:</span> @Model.Input.Username</p>
                    <p class="d-inline ml-3"><span class="mark">Created On:</span> @Model.Input.Created</p>
                    <p class="d-inline ml-3"><span class="mark">Farm Name:</span> @Model.Input.FarmName</p>

                    @* Posted By: <input class="text-muted" type="text" asp-for="User.Identity.Name" readonly>
                        @* Farm Name: <input type="text" asp-for="Input.Farm.Name" readonly> *@
                    @* <span class="ml-2">Created On: </span> <input class="text-muted" type="date"
                        asp-for="Input.Created"
                        readonly> *@

                    <div class="form-group">
                        <label asp-for="Input.Message"></label>
                        <textarea asp-for="Input.Message" class="form-control" cols="30" rows="10"></textarea>
                        @* <input asp-for="Input.Message" class="form-control" /> *@
                        <span asp-validation-for="Input.Message" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Input.Rating"></label>
                        <input asp-for="Input.Rating" class="form-control" type="number" />
                        <span asp-validation-for="Input.Rating" class="text-danger"></span>
                    </div>

                    <div class="btn-group">
                        <a asp-page="/Account/UserProfile" class="btn btn-md btn-primary mr-4" role="button">Cancel</a>
                        <button type="submit" class="btn btn-primary btn-md mr-4">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>


@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/EditUser.cshtml
@page "{id}"
@model MyFarmer.Pages.Account.EditUserModel
@{
    ViewData["Title"] = "EditUser";
}

<div class="container">
    <div class="text-center">
        <h1 class="text-warning profile-header">Edit My Info:</h1>
    </div>

    <div class="container d-flex justify-content-center mt-5" style="margin-bottom: 10rem !important;">
        <div class="card w-75">
            <div class="card-body">

                <form method="POST">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="Input.UserId">
                    <div class="form-group">
                        <label asp-for="Input.Username"></label>
                        <input asp-for="Input.Username" class="form-control" readonly />
                        <span asp-validation-for="Input.Username" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Input.Email"></label>
                        <input asp-for="Input.Email" class="form-control" />
                        <span asp-validation-for="Input.Email" class="text-danger"></span>
                    </div>

                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary btn-md mr-4">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>


@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/Login.cshtml
@page
@model MyFarmer.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login in";
}
<div class="container">
    @if (Model.Message != null)
    {
        <div>
            <div class="alert alert-success">
                @Model.Message
            </div>
        </div>
    }
    <div class="row">
    <div class="col-sm-6 offset-3">
        <h4>User login</h4>
        <hr />
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Password"></label>
                <input asp-for="Input.Password" class="form-control" />
                <span asp-validation-for="Input.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>
                    <a asp-page="Register">Register as a new user</a>
                </p>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/Logout.cshtml
@page
@model MyFarmer.Pages.Account.LogoutModel
@{
    ViewData["Title"] = "User logged out";
}
<h1>@ViewData["Title"]</h1>
@{
    <p>You've been logged out
        <a class="nav-link" asp-area="" asp-page="/Index">Click to continue.</a>
    </p>
}

MyFarmer/Pages/Account/Register.cshtml
@page
@model MyFarmer.Pages.Account.RegisterModel
@{
    ViewData["Title"] = "Register";
}
<div class="container">
    <div class="row">
    <div class="col-md-6 offset-3">
        <form method="post">
            <h4>Create a new account.</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Password"></label>
                <input asp-for="Input.Password" class="form-control" />
                <span asp-validation-for="Input.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.ConfirmPassword"></label>
                <input asp-for="Input.ConfirmPassword" class="form-control" />
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-check">
                <input asp-for="Input.RegisterMeAsFarmer" class="form-check-input" id="isFarmerLoginTypeChecked"/>
                <label asp-for="Input.RegisterMeAsFarmer" class="form-check-label">
                    Register me as a farmer
                </label>
            </div>
            <div id="farmerRegistratioConfirmation" style="display:none">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="farmLoginConfirmation">
                    <label class="form-check-label" for="farmLoginConfirmation">
                        <span class="text-danger">Are you sure you want to register farm login? It may restricts your permissions.</span>
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary" id="registerSaveBtn">Register</button>
        </form>
    </div>
</div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MyFarmer/Pages/Account/RegisterSuccess.cshtml
@page
@model MyFarmer.Pages.Account.RegisterSuccessModel
@{
    ViewData["Title"] = "Register confirmation";
}
<h1>@ViewData["Title"]</h1>
@{
    <p>Registration succeeded with email @Model.Email
        <a class="nav-link" asp-area="" asp-page="Login">Click here to log in.</a>
    </p>
}